# Commands the robot to move the wheels for
# an specific time
#
# Left wheel speed
std_msgs/Int8 lspeed
# Right wheel speed
std_msgs/Int8 rspeed
# Time in miliseconds
std_msgs/Int32 time
# Identifier for end-of-movement notification
std_msgs/Int16 unlockid
---
std_msgs/Int8 error
