# Commands the robot to show an emotion in the display
#
# String of the emotion to show. Posible values:
# happy, laughing, sad, angry, surprised, normal.
std_msgs/String emotion
---
std_msgs/Int8 error
