# Commands the robot to change the frequency of notifications
# of all sensors of the robot
#
# Integer representing the frequency; posible values: 
# 0 for LOW
# 1 for NORMAL
# 2 for HIGH
# 3 for MAX
std_msgs/Int8 frequency 
---
std_msgs/Int8 error
