# Represents all IR sensor data of the Rob base
#
# Sensor at the center of the front of the base
sensor_msgs/Range FrontC
# Sensor at the right center of the front of the base
sensor_msgs/Range FrontR
# Sensor at the right of the front of the base
sensor_msgs/Range FrontRR
# Sensor at the left center of the front of the base
sensor_msgs/Range FrontL
# Sensor at the left of the front of the base
sensor_msgs/Range FrontLL
# Sensor at the center of the back of the base
sensor_msgs/Range BackC
# Sensor at the right of the back of the base
sensor_msgs/Range BackR
# Sensor at the left of the back of the base
sensor_msgs/Range BackL
